In [1]:
import numpy as np

### 1. Numpy Array and Operation

- numpy의 기본적인 사용법에 대해서 배워봅니다.


- numpy에서 numpy.array를 만드는 여러가지 방법과 지원하는 연산자에 대해서 공부합니다.


< numpy array의 특징 >
1. 모든 원소의 dtype이 같다.

2. 연산의 의미가 조금 다르다. (broadcasting)

3. 대용량 array인 경우에 for문을 직접 사용하는 것보다 내부적으로 정의된 연산을 사용하는게 더 빠르다.

4. 생성 후에 크기 변경이 불가능하다.

### 1.1. Numpy Array creation

In [2]:
data = [1, 2, 3, 4]
np.array(data)

array([1, 2, 3, 4])

In [5]:
data2 = [[1, 2], 
         [3, 4]]
arr2 = np.array(data2)
arr2.shape

(2, 2)

In [6]:
# 0부터 9까지 숫자를 자동으로 생성한 array
np.arange(0, 10)
np.zeros(shape=(5, 3))
np.linspace(0, 1, 100) # [start, stop]에서 num개의 number를 균등한 구간으로 잘라서 원소를 생성.
np.random.randn(5, 3)  # 주어진 shape을 가지는 numpy array를 만들어주는데, 원소는 표준정규분포에서 sampling.

array([[-2.29156114,  0.98138576,  0.0735142 ],
       [ 0.64898323,  0.40222537, -0.23131237],
       [-1.01101436,  0.07909985,  0.99006783],
       [-0.96488607,  0.85837019,  0.45079753],
       [-1.20289577, -1.31985769, -0.3670272 ]])

In [7]:
# 10부터 99까지 숫자를 자동으로 생성한 array
test = np.arange(10, 100)
print(test)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57
 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81
 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]


### 1.2. Reshaping array

In [8]:
## 1차원 : 벡터
## 2차원 : 행렬
## 3차원 이상 : 텐서

## array의 shape은 가장 바깥 괄호 '['부터 원소의 개수를 순차적으로 기록한 것.
x = np.zeros(shape=(5, 3, 4))
print(x)

## 224 x 224 크기의 RGB channel을 가지고 있는 이미지가 32개다.
x = np.zeros(shape=(32, 3, 224, 224))

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [9]:
x = np.arange(1, 10).reshape(3, 3)
print(x.shape)
print(x)

(3, 3)
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [10]:
# reshape을 이용하여 만들어봅시다.
# 주의1 - (9, )와 (9, 1)의 결과는 완전히 다르다.
# 주의2 - 새로운 형태로 배열을 재구성할 때 원래 배열의 원소 수와 정확히 일치해야 한다.

x1 = np.arange(1, 10).reshape(9,)
print(x1.shape)
print(x1)

x2 = np.arange(1, 10).reshape(9, 1)
print(x2.shape)
print(x2)

(9,)
[1 2 3 4 5 6 7 8 9]
(9, 1)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


### 1.3. Concatenation of arrays

In [18]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

arr3 = np.concatenate((arr1, arr2), axis=0)
print(arr3.shape)
print(arr3)

(6,)
[1 2 3 4 5 6]
(6,)
[1 2 3 4 5 6]


In [15]:
# stacking vertically
np.vstack([arr1, arr2])

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
# stacking horizontally
np.hstack([arr1, arr2])

array([1, 2, 3, 4, 5, 6])

## 1.4. Array Arithmetic (like vector) --> Universal Function

In [19]:
## 벡터 연산
v1 = np.array((1, 2, 3))
v2 = np.array((4, 5, 6))

print(v1 + v2)
print(v1 - v2)
print(v1 * v2)
print(v1 / v2)
print(v1 @ v2) ## dot product

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
32


### 1.5. Broadcast and Universal Function

서로 다른 크기의 배열 간에 산술 연산을 수행할 수 있게 해주는 메커니즘. 효율적으로 대규모 배열 연산을 수행할 수 있게 한다.

- 규칙 1: 배열의 차원 수가 다르면, 차원 수가 적은 배열의 형태가 차원 수가 더 많은 배열의 형태와 같아질 때까지 왼쪽에 1을 추가합니다.  
- 규칙 2: 특정 차원에서 크기가 다른 경우, 그 차원의 크기가 1인 배열이 다른 배열의 해당 차원 크기에 맞춰 확장됩니다.  

서로 크기가 다른 numpy array를 연산할 때, 자동으로 연산을 전파(broadcast)해주는 기능. 행렬곱 연산을 할 때 편리하다.

In [20]:
a = np.array([1, 2, 3])      # 1차원 배열 (3,)
b = np.array([[1], [2], [3]]) # 2차원 배열 (3,1)

# a는 1x3으로 확장되고, b는 각 행에 대해 1x3으로 확장됩니다.
print(a + b)

[[2 3 4]
 [3 4 5]
 [4 5 6]]


In [21]:
a = np.array([1, 2, 3])    # 1차원 배열 (3,)
b = np.array([10, 20, 30]) # 1차원 배열 (3,)

# a는 (1, 3)으로 확장되고, b는 (3, 1)으로 확장되어 최종적으로 (3, 3) 배열이 됩니다.
print(a[:, np.newaxis] + b)

[[11 21 31]
 [12 22 32]
 [13 23 33]]


- Universal Function : broadcast 기능을 확장해서, numpy array의 모든 원소에 동일한 함수를 반복문으로 적용한 것과 같은 효과를 내는 기능.

In [22]:
# f = lambda x : 1/x
arr1 / 1  ## int -> float

## Universal Function
1 / arr1  ## 각 원소를 reverse 연산.

def reverse_num(x):
    return 1/x
for i in range(len(arr1)):
    arr1[i] = reverse_num(arr1[i])

## 2. Numpy Methods

- numpy에서 사용되는 여러가지 함수들을 사용해봅시다.

### 2.1. Math Functions 

In [23]:
# 표준정규분포에서 random sampling을 한 원소를 가지는 5x3 행렬을 만든다.
# pseudo-random : 현재 시각(ns)
np.random.seed(42)   # set seed number
mat1 = np.random.randn(5, 3)
mat1

array([[ 0.49671415, -0.1382643 ,  0.64768854],
       [ 1.52302986, -0.23415337, -0.23413696],
       [ 1.57921282,  0.76743473, -0.46947439],
       [ 0.54256004, -0.46341769, -0.46572975],
       [ 0.24196227, -1.91328024, -1.72491783]])

In [24]:
# mat1에 절대값 씌우기
np.abs(mat1)

array([[0.49671415, 0.1382643 , 0.64768854],
       [1.52302986, 0.23415337, 0.23413696],
       [1.57921282, 0.76743473, 0.46947439],
       [0.54256004, 0.46341769, 0.46572975],
       [0.24196227, 1.91328024, 1.72491783]])

In [25]:
# mat1 제곱하기
np.square(mat1)

array([[0.24672495, 0.01911702, 0.41950044],
       [2.31961994, 0.0548278 , 0.05482011],
       [2.49391312, 0.58895606, 0.2204062 ],
       [0.2943714 , 0.21475596, 0.2169042 ],
       [0.05854574, 3.66064129, 2.97534153]])

In [26]:
# mat1의 제곱근 구하기
np.sqrt(mat1.astype('complex')) # nan = not a number

array([[0.70477951+0.j        , 0.        +0.37183908j,
        0.80479099+0.j        ],
       [1.23411096+0.j        , 0.        +0.48389397j,
        0.        +0.48387701j],
       [1.25666734+0.j        , 0.87603352+0.j        ,
        0.        +0.68518201j],
       [0.73658675+0.j        , 0.        +0.68074789j,
        0.        +0.68244396j],
       [0.49189661+0.j        , 0.        +1.38321374j,
        0.        +1.31336127j]])

In [27]:
# linear algebra functions
vec = np.array([1, 2, 3])

# 1. norm
np.linalg.norm(vec)

# 2. eigenvalue
mat = np.array([[1, 0],
                [0, 1]])
np.linalg.eig(mat)

(array([1., 1.]),
 array([[1., 0.],
        [0., 1.]]))

### 2.2. Aggregation functions 

In [28]:
np.random.seed(0xC0FFEE)
mat2 = np.random.rand(3, 2)
mat2

array([[0.57290783, 0.81519505],
       [0.92585076, 0.09358959],
       [0.26716135, 0.96059676]])

In [30]:
np.sum(mat2)

3.635301352873192

In [29]:
# Summation
# axis=0 : 세로방향(=column방향), axis=1 : 가로방향(=row방향)
np.sum(mat2, axis=1)

array([1.38810288, 1.01944035, 1.22775812])

In [31]:
# mean
np.mean(mat2, axis=0)

array([0.58863998, 0.62312714])

In [32]:
# std
np.std(mat2, axis=1)

array([0.12114361, 0.41613058, 0.3467177 ])

In [33]:
# min, max
np.min(mat2)
np.max(mat2, axis=1)

array([0.81519505, 0.92585076, 0.96059676])

In [34]:
# 최소값이 있는 Index
np.argmin(mat2, axis=1)

array([0, 1, 0])

In [35]:
# 최대값이 있는 Index
np.argmax(mat2, axis=0)

array([1, 2])

## 3. Performance Check
- Universal Function 기능을 통해 반복문을 사용한 것보다 훨씬 빠른 성능을 냅니다.


- 직접 실험을 통해 그 차이를 확인해보겠습니다.

In [36]:
np.random.seed(0)

def reverse_num(values):
    output = np.empty(len(values))
    
    for i in range(len(values)):
        output[i] = 1.0 / values[i]
    
    return output

In [37]:
# 1부터 100까지 범위에서 1000000개를 랜덤으로 뽑아서 array를 만듭니다.
big_array = np.random.randint(1, 100, 10000000)

In [38]:
%timeit reverse_num(big_array)

2.17 s ± 53.5 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [39]:
%timeit 1.0 / big_array

23.1 ms ± 255 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
